trigger:
  branches:
    include:
      - main
      - feature/*

pool:
  vmImage: 'ubuntu-latest'

workspace:
  clean: all

variables:
  containerRegistry: container-registry-aco-common
  personalisationPath: 'packages/personalisation'
  monitoringPath: 'packages/monitoring'
  myStayPath: 'packages/mystay'
  receiverPath: 'packages/receiver'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - script: |
      npm install -g yarn
    displayName: 'Install Yarn'

  - script: |
      yarn global add lerna
    displayName: 'Install Lerna'

  - script: |
      lerna bootstrap --concurrency 4 --npm-client=yarn
      lerna run build
    displayName: 'Install dependencies and build'


  - task: Docker@2
    displayName: 'Login to Docker Registry'
    inputs:
      containerRegistry: $(containerRegistry)

  - script: |
      docker build -t $(containerRegistry)/receiver:$(Build.BuildId) -f $(receiverPath)/Dockerfile .
      docker build -t $(containerRegistry)/personalisation:$(Build.BuildId) -f $(personalisationPath)/Dockerfile .
      docker build -t $(containerRegistry)/monitoring:$(Build.BuildId) -f $(monitoringPath)/Dockerfile .
      docker build -t $(containerRegistry)/myStayPath:$(Build.BuildId) -f $(myStayPath)/Dockerfile .
    displayName: 'Build Docker Images'

  - script: |
      docker push $(containerRegistry)/receiver:$(Build.BuildId)
      docker push $(containerRegistry)/personalisation:$(Build.BuildId)
      docker push $(containerRegistry)/monitoring:$(Build.BuildId)
      docker push $(containerRegistry)/myStayPath:$(Build.BuildId)
    displayName: 'Push Docker Images'
